# Generated by Django 3.2.25 on 2026-05-08 21:54

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191018_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuses',
            options={'ordering': ['id'], 'verbose_name': '校区表', 'verbose_name_plural': '校区表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'ordering': ['id'], 'verbose_name': '班级表', 'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='consultrecord',
            options={'ordering': ['id'], 'verbose_name': '跟进记录表', 'verbose_name_plural': '跟进记录表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'ordering': ['id'], 'verbose_name': '课程记录表', 'verbose_name_plural': '课程记录表'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name': '部门表', 'verbose_name_plural': '部门表'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['id'], 'verbose_name': '报名表', 'verbose_name_plural': '报名表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'ordering': ['id'], 'verbose_name': '学习记录', 'verbose_name_plural': '学习记录'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['id'], 'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.AddField(
            model_name='customer',
            name='delete_status',
            field=models.BooleanField(default=False, verbose_name='删除状态'),
        ),
        migrations.AlterField(
            model_name='campuses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.CharField(choices=[('LinuxL', 'Linux 中高级'), ('PythonFullStack', 'Python 高级全栈开发')], max_length=64, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='status',
            field=models.CharField(choices=[('A', '近期无报名计划'), ('B', '1 个月内报名'), ('C', '2 周内报名'), ('D', '1 周内报名'), ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效')], help_text='选择客户此时的状态', max_length=8, verbose_name='跟进状态'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, default=None, help_text='格式 yyyy-mm-dd', null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('LinuxL', 'Linux 中高级'), ('PythonFullStack', 'Python 高级全栈开发')], max_length=22, verbose_name='咨询课程'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号格式不正确')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(help_text='QQ 号必须唯一', max_length=64, unique=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ 昵称'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('qq', 'QQ 群'), ('referral', '内部转介绍'), ('website', '官方网站'), ('baidu_ads', '百度推广'), ('office_direct', '直接上门'), ('WoM', '口碑'), ('public_class', '公开课'), ('website_luffy', '路飞官网'), ('others', '其它')], default='qq', max_length=64, verbose_name='客户来源'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='contract_approved',
            field=models.BooleanField(default=False, help_text='在审阅完学员的资料无误后勾选此项，合同即生效', verbose_name='审批通过'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='homework',
            field=models.FileField(blank=True, default=None, null=True, upload_to='homeworks/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'zip', 'txt'])], verbose_name='作业文件'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
